[workspace]
resolver = "3"
members = [
    "accordion-rs",
    "alert-rs",
    "eld",
    "i18n-rs",
    "image-rs",
    "input-rs",
    "navbar",
    "radio-rs",
    "scroll-rs",
    "select-rs",
    "sidebar",
    "skeleton-rs",
    "slider-rs",
    "table-rs",
]